name: Busca Diária de Licitações PNCP

on:
  schedule:
    - cron: '0 12 * * *'  # Executa todos os dias às 12:00 UTC (9:00 no horário de Brasília)
  workflow_dispatch:  # Permite execução manual

jobs:
  buscar-licitacoes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2
      
    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Executar script de busca de licitações
      run: |
        python busca_licitacoes_pncp.py
      env:
        EMAIL_REMETENTE: ${{ secrets.EMAIL_REMETENTE }}
        EMAIL_SENHA: ${{ secrets.EMAIL_SENHA }}
        EMAIL_DESTINATARIO: ${{ secrets.EMAIL_DESTINATARIO }}
        
    - name: Salvar resultados como artefato
      uses: actions/upload-artifact@v2
      with:
        name: resultados-licitacoes
        path: resultados_licitacoes/
        retention-days: 30
